### ISSUE TITLE
Question on integration

### ISSUE THREAD

**Issue by istvano** [nekcih/GASL#1]
Hi,

Great job on this little JS script. I stumbled upon it while looking for a way to integrate GA into Storyline.

What did you use to add the  script include to the published "story.html" ? We have 20+ projects and I am wondering if you wrote a small script or you do this step manually?

I would appreciate any suggestions.

Kind Regards,

Istvan

**Comment by markhicken** [comment]
We did it manually. I would love to hook in to the Storyline publishing process but unfortunately, I couldn't find an easy way to do that.

**Comment by istvano** [comment]
Hi,

thanks for the update. I am thinking about creating a small script to do it. 

Regards,
